name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # or master, depending on your default branch
  workflow_dispatch:  # Allows manual triggering

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: line-inventory-bot
  REGION: asia-northeast1  # Tokyo region, change as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and push container
        run: |
          docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }} .
          docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }} \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated \
            --set-env-vars="NODE_ENV=production" \
            --update-secrets="CHANNEL_ACCESS_TOKEN=CHANNEL_ACCESS_TOKEN:latest,CHANNEL_SECRET=CHANNEL_SECRET:latest,SPREADSHEET_ID=SPREADSHEET_ID:latest,GOOGLE_APPLICATION_CREDENTIALS_JSON=GOOGLE_APPLICATION_CREDENTIALS_JSON:latest,LINE_GROUP_IDS=LINE_GROUP_IDS:latest" \
            --service-account="github-actions-service-account@$PROJECT_ID.iam.gserviceaccount.com"

      - name: Show deployed service URL
        run: |
          echo "Service deployed to: $(gcloud run services describe $SERVICE_NAME --region $REGION --format 'value(status.url)')" 