name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
      - master

env:
  PROJECT_ID: lengolf-operations
  SERVICE_NAME: line-bot
  REGION: asia-northeast1
  REPOSITORY: line-bot-images  # Artifact Registry repository name
  LOCATION: asia-northeast1    # Artifact Registry location

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Create Artifact Registry repository if it doesn't exist
      run: |
        if ! gcloud artifacts repositories describe $REPOSITORY --location=$LOCATION; then
          gcloud artifacts repositories create $REPOSITORY --repository-format=docker --location=$LOCATION
        fi

    - name: Authorize Docker push to Artifact Registry
      run: |
        gcloud auth configure-docker $LOCATION-docker.pkg.dev

    - name: Build and push Docker image
      run: |
        docker build -t $LOCATION-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
        docker push $LOCATION-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image $LOCATION-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
          --platform managed \
          --region ${{ env.REGION }} \
          --allow-unauthenticated \
          --set-env-vars="CHANNEL_ACCESS_TOKEN=${{ secrets.CHANNEL_ACCESS_TOKEN }},CHANNEL_SECRET=${{ secrets.CHANNEL_SECRET }},SPREADSHEET_ID=${{ secrets.SPREADSHEET_ID }},LINE_GROUP_IDS=${{ secrets.LINE_GROUP_IDS }}" \
          --service-account="github-actions@lengolf-operations.iam.gserviceaccount.com"

    - name: Show deployed service URL
      run: gcloud run services describe ${{ env.SERVICE_NAME }} --platform managed --region ${{ env.REGION }} --format 'value(status.url)' 