name: Weekly Inventory Update

on:
  schedule:
    # Runs at 8:30 AM Bangkok time (UTC+7) every Monday
    # Note: GitHub Actions uses UTC time, so 01:30 UTC = 08:30 Bangkok
    - cron: '30 1 * * 1'
  # Allow manual triggering for testing
  workflow_dispatch:
    inputs:
      sheet_name:
        description: 'Google Sheet Tab Name'
        required: false
        default: 'Last Entry'
      start_cell:
        description: 'Start Cell (e.g., A2)'
        required: false
        default: 'B12'
      end_cell:
        description: 'End Cell Column (e.g., E)'
        required: false
        default: 'D'

jobs:
  inventory-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run inventory update
        env:
          CHANNEL_ACCESS_TOKEN: ${{ secrets.CHANNEL_ACCESS_TOKEN }}
          CHANNEL_SECRET: ${{ secrets.CHANNEL_SECRET }}
          SPREADSHEET_ID: "1e0D6-6CcSrrVr4SnV4-DaOw0gtODJaSYLmvU8j83N1o"
          LINE_GROUP_IDS: ${{ secrets.LINE_GROUP_IDS }}
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
          SHEET_NAME: "Last Entry"
          START_CELL: "B12"
          END_CELL: "D"
        run: python src/inventory/update.py 